// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydTAA6JqTjqz8uhVh90sUY7m50dL6VaI',
    appId: '1:61356988395:android:92546bd45eeb9a0ccdebae',
    messagingSenderId: '61356988395',
    projectId: 'zencloud-8c137',
    storageBucket: 'zencloud-8c137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSyvW5c1v9jMcBMSUreMC3f4HCay-NdU',
    appId: '1:61356988395:ios:098be7c74b04fbedcdebae',
    messagingSenderId: '61356988395',
    projectId: 'zencloud-8c137',
    storageBucket: 'zencloud-8c137.appspot.com',
    iosClientId: '61356988395-rmttjjjl2gcif7qe7937krkvbfnpdtmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgSyvW5c1v9jMcBMSUreMC3f4HCay-NdU',
    appId: '1:61356988395:ios:7a85581441d3fb75cdebae',
    messagingSenderId: '61356988395',
    projectId: 'zencloud-8c137',
    storageBucket: 'zencloud-8c137.appspot.com',
    iosClientId: '61356988395-47qm3tfjqli393scnncif4hha5os3cm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.meditationapp',
  );
}
